#cp ../init.vim ~/.config/nvim/init.vim
#cp tmux.conf.local ~/.tmux.conf.local
cp bashrc21 ~/.bashrc
cp ../ideavimrc ~/.ideavimrc
cp ../condarc ~/.condarc
cp ../gitignore ~/.gitignore
cp p10k.zsh ~/.p10k.zsh
cp ../vimrc ~/.vimrc
cp zshrc ~/.zshrc
