alias typora="open -a typora"
alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias vi='nvim'
alias grep="grep --color=auto"
alias subl=\''/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'\'
alias sm='subl ~/githubWdf/idl-sfmessageslang'
alias sb='subl ~/githubWdf/blog'
alias tb='typora ~/githubWdf/blog'
alias cdb='cd ~/githubWdf/blog'
alias cdbc='cd ~/githubP/blog-content'
alias sbc='subl ~/githubP/blog-content'
alias csa='code ~/githubP/stock-analyzer'
alias oc='open ~/githubP/stock-analyzer/data/charts'
alias ot='open https://itsm.services.sap/now/workspace/agent/list & open https://jira.successfactors.com/issues/\?filter=-1'
alias pjc='/Users/i312177/.conda/envs/stock-analyzer/bin/python ~/githubWdf/cmd-shortcut/jenkins-checker.py'
alias psrv='python -m SimpleHTTPServer 8001'

export PYTHON3="/Users/i312177/opt/anaconda3"
export ZOOKEEPER_HOME="/usr/local/opt/apache-zookeeper-3.6.2-bin"
export JMETER_HOME="/usr/local/opt/apache-jmeter-5.4"
export SMERGE_HOME=/Users/i312177/software/Sublime\ Merge.app/Contents/SharedSupport/bin
export GIT_EXTERNAL_DIFF=smerge
export MYSQL_HOME=/usr/local/mysql
export JAVA_HOME=/Library/Java/JavaVirtualMachines/sapjvm8/Contents/Home
export CLASS_PATH=$JAVA_HOME/lib
export ANT_HOME=/usr/local/opt/apache-ant-1.9.15
export MVN_HOME=/usr/local/opt/apache-maven-3.6.3
export ANT_OPTS='-Xms1024M -Xmx4096M -XX:MaxPermSize=512m'
export IVY_SERVER=http://ivyrot.sfdp.c.eu-de-2.cloud.sap:8081
export MAVEN_OPTS='-Xmx3000m'
export SFS_BIND_PORT_SHUTDOWN=8006
export ICU4V_HOME=/usr/local/opt/icu4c/
export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"
export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"

export PATH=$PATH:${JAVA_HOME}/bin:${MVN_HOME}/bin:${ANT_HOME}/bin:${ICU4V_HOME}/bin:${ICU4V_HOME}/sbin:${MYSQL_HOME}/bin:${PYTHON3}/bin:/usr/local/Cellar/neovim/0.4.4.reinstall/bin:${ZOOKEEPER_HOME}/bin:${JMETER_HOME}/bin:${SMERGE_HOME}
