cp ~/.config/nvim/init.vim ../init.vim
cp ~/.bashrc bashrc
cp ~/.ideavimrc ../ideavimrc
cp ~/.condarc ../condarc
cp ~/.gitignore ../gitignore
cp ~/.p10k.zsh ../p10k.zsh
cp ~/.vimrc ../vimrc
cp ~/.zshrc zshrc
cp ~/.tmux.conf tmux.conf
cp ~/.tmux.conf.local tmux.conf.local
cp /etc/profile profile
