alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias vi='nvim'
alias grep="grep --color=auto"
alias typora="open -a typora"
alias pshell="powershell.exe"
alias start='/mnt/c/Windows/explorer.exe'
alias cmd="cmd.exe"
alias java='java.exe'
alias javac='javac.exe'
alias hashcat='hashcat.exe'
alias chrome='"/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"'
alias subl='"/mnt/c/Program Files/Sublime Text/sublime_text.exe"'
alias smerge='"/mnt/c/Program Files/Sublime Merge/sublime_merge.exe"'
alias rar='"/mnt/c/Program Files/WinRAR/WinRAR.exe"'
alias code='"/mnt/c/Users/I312177/AppData/Local/Programs/Microsoft VS Code/Code.exe"'
alias cdbc='cd /mnt/c/githubP/blog-content'
alias sbc='subl /mnt/c/githubP/blog-content'
alias vbc='vi  /mnt/c/githubP/blog-content'
alias ssa='subl /mnt/c/githubP/stock-analyzer'
alias oc='start /mnt/c/githubP/stock-analyzer/data/charts'
alias psrv='python -m SimpleHTTPServer 8001'

export JAVA_HOME='/mnt/c/install/sapjvm_8/'
export CLASS_PATH=$JAVA_HOME/lib
export MVN_HOME='/mnt/d/install/apache-maven-3.6.1'
export ANT_OPTS='-Xms1024M -Xmx4096M -XX:MaxPermSize=512m'
export MAVEN_OPTS='-Xmx3000m'
export MYSQL_HOME='/mnt/c/Program Files/MySQL/MySQL Shell 8.0'
export PYTHON3="/mnt/c/Users/i312177/AppData/Local/Continuum/anaconda3"
export ZOOKEEPER_HOME="/mnt/c/install/apache-zookeeper-3.6.1-bin"
export JMETER_HOME="/usr/local/opt/apache-jmeter-5.4"
export SMERGE_HOME="/mnt/c/Program Files/Sublime Merge/"
export GIT_EXTERNAL_DIFF=smerge
export GRADLE_HOME='/mnt/c/install/gradle-6.5.1'
export POWERSHELL_HOME='/mnt/c/WINDOWS/system32/WindowsPowerShell/v1.0/'
export CMD_HOME='/mnt/c/WINDOWS/system32/'
export HASHCAT_HOME='/mnt/c/install/hashcat-6.2.5'
export HASHCATUTILS_HOME='/mnt/c/install/hashcat-utils-1.9'
export JTR_HOME='/mnt/c/install/john-1.9.0-jumbo-1-win64'

export PATH=$PATH:${JAVA_HOME}/bin:${MVN_HOME}/bin:${ANT_HOME}/bin:${ICU4V_HOME}/bin:${ICU4V_HOME}/sbin:${MYSQL_HOME}/bin:${PYTHON3}/bin:${ZOOKEEPER_HOME}/bin:${JMETER_HOME}/bin:${SMERGE_HOME}:${GRADLE_HOME}/bin:${HASHCAT_HOME}:${JTR_HOME}/run:${HASHCATUTILS_HOME}/bin:${POWERSHELL_HOME}:${CMD_HOME}
if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi

